### PR TITLE
SCALRCORE-25897: Remove ReadBySemanticVersion && make validString && …

### PR DESCRIPTION
**Pull request by kozliuk**
…validStringID public

### CODE REVIEW

**Review by petroprotsakh — APPROVED** [review]

**Comment by emocharnik** [comment]
@kozliuk, Required builds are failing.

**Comment by emocharnik** [comment]
@kozliuk, Required builds are failing.

**Comment by emocharnik** [comment]
@kozliuk, Required builds are failing.

**Comment by emocharnik** [comment]
@kozliuk, Required builds are failing.

**Comment by emocharnik** [comment]
@kozliuk, Required builds are failing.

**Comment by emocharnik** [comment]
@kozliuk, Required builds are failing.

**Comment by emocharnik** [comment]
@kozliuk, Required builds are failing.

**Comment by emocharnik** [comment]
@kozliuk, Required builds are failing.

**Comment by emocharnik** [comment]
@kozliuk, Required builds are failing.

**Comment by emocharnik** [comment]
@kozliuk, Required builds are failing.

**Comment by emocharnik** [comment]
@kozliuk, Required builds are failing.

**Comment by emocharnik** [comment]
@kozliuk, Required builds are failing.

**Comment by emocharnik** [comment]
@kozliuk, Required builds are failing.

**Comment by emocharnik** [comment]
@kozliuk, Required builds are failing.

**Comment by emocharnik** [comment]
@kozliuk, Required builds are failing.

**Comment by emocharnik** [comment]
@kozliuk, Required builds are failing.

**Comment by emocharnik** [comment]
@kozliuk, Required builds are failing.

**Comment by emocharnik** [comment]
@kozliuk, Required builds are failing.

**Comment by emocharnik** [comment]
@kozliuk, Required builds are failing.

**Comment by emocharnik** [comment]
@kozliuk, Required builds are failing.

**Comment by emocharnik** [comment]
@kozliuk, Required builds are failing.

**Comment by emocharnik** [comment]
@kozliuk, Required builds are failing.

**Comment by emocharnik** [comment]
@kozliuk, Required builds are failing.

**Comment by emocharnik** [comment]
@kozliuk, Required builds are failing.

**Comment by emocharnik** [comment]
@kozliuk, Required builds are failing.

**Comment by emocharnik** [comment]
@kozliuk, Required builds are failing.

**Comment by emocharnik** [comment]
@kozliuk, Required builds are failing.

**Comment by emocharnik** [comment]
@kozliuk, Required builds are failing.

**Comment by emocharnik** [comment]
@kozliuk, Required builds are failing.

**Comment by emocharnik** [comment]
@kozliuk, Some non-required builds are failing or stuck.

**Pull request merged**
