### PR TITLE
SCALRCORE-31215 > Add ReadOutputs function for workspace

### PR DESCRIPTION
**Pull request by artemvang**

### CODE REVIEW

**Comment by artemvang** [comment]
Тести зараз не проходять бо workspaces/<ws>/outputs зараз в internal профілі, цей PR переводить у preview https://github.com/Scalr/fatmouse/pull/8306

**Review by petroprotsakh — APPROVED** [review]

**Comment by petroprotsakh** [comment]
> Був настрій і тому тут же додав можливість парсити jsonapi links.

But Links support was removed in later commits?
<sub>Nit: i'ts better to comment in English in public repos.</sub>

**Review by vmotso — CHANGES_REQUESTED** [review]
@artemvang in this PR we need to remove redundant logic
https://github.com/Scalr/go-scalr/blob/master/run.go#L102

and simplify operator

```go
run, err := w.scalrClient.Client.Runs.Create(ctx, scalr.RunCreateOptions{
	Workspace: &scalr.Workspace{
		ID: w.instance.Status.WorkspaceID,
	},
	ConfigurationVersion: &scalr.ConfigurationVersion{
		ID: w.instance.Status.ConfigurationVersion.ID,
	},
})
```
->
```go
run, err := w.scalrClient.Client.Runs.Create(ctx, scalr.RunCreateOptions{
	Workspace: &scalr.Workspace{
		ID: w.instance.Status.WorkspaceID,
	},
})

```

**Comment by artemvang** [comment]
> But Links support was removed in later commits?

@petroprotsakh yep, we do not need them for now

**Review by vmotso — APPROVED** [review]

**Pull request merged**
